"""
Django settings for core project.
Generated by 'django-admin startproject' using Django 5.2.1
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

from pathlib import Path
STATICFILES_DIRS = [BASE_DIR / "frontend" / "assets"]  # Logos liegen hier

SECRET_KEY = "django-insecure-wzd=*-@9so+oodbdctrw#+re0rt@h6k7@_k@q-^tq+j21snet2"
DEBUG      = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "leorullani.com",
    "kanban.leorullani.com.w020313e.kasserver.com",
    "www.leorullani.com",
    "91.99.137.136",
]

# ---------------------------------------------------------------------------
# Apps
# ---------------------------------------------------------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "django_extensions",
    # --- project apps ---
    "auth_app",
    "kanban_app",
]

AUTH_USER_MODEL = "auth_app.User"

# ---------------------------------------------------------------------------
# Middleware
# ---------------------------------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOW_ALL_ORIGINS = True  # lokal entspannt – in Prod einschränken

# ---------------------------------------------------------------------------
# Templates  ←  hier Pfad zu /templates/ ergänzt
# ---------------------------------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],           # <‑‑ hinzugefügt
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ROOT_URLCONF    = "core.urls"
WSGI_APPLICATION = "core.wsgi.application"

# ---------------------------------------------------------------------------
# Datenbank
# ---------------------------------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# ---------------------------------------------------------------------------
# Auth / i18n etc.  (unverändert)
# ---------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "en-us"
TIME_ZONE     = "UTC"
USE_I18N      = True
USE_TZ        = True

# ---------------------------------------------------------------------------
# Static / Media  (optional STATICFILES_DIRS ergänzt)
# ---------------------------------------------------------------------------
STATIC_URL  = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

#  Falls du BBM- & SFL‑Logos aus frontend/assets im PDF einbinden willst:
STATICFILES_DIRS = [
    BASE_DIR / "frontend" / "assets",   # <‑‑ optional – passt Pfad an deine Struktur an
]

# ---------------------------------------------------------------------------
# REST‑Framework
# ---------------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ["rest_framework.authentication.TokenAuthentication"],
    "DEFAULT_PERMISSION_CLASSES":     ["rest_framework.permissions.IsAuthenticated"],
}

# ---------------------------------------------------------------------------
# Mail
# ---------------------------------------------------------------------------
EMAIL_BACKEND       = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST          = "mail.bbmproductions.ch"
EMAIL_PORT          = 587
EMAIL_HOST_USER     = "leugzim.rullani@bbmproductions.ch"
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS       = True
DEFAULT_FROM_EMAIL  = EMAIL_HOST_USER

DEFAULT_AUTO_FIELD  = "django.db.models.BigAutoField"